### ISSUE TITLE
Apply ternary operator to manage a conditional in your variables

### ISSUE THREAD

**Issue by keikeka** [cornensue/Conditional-Profile-Card#1]
Cornelio, 
In this line, you must apply a ternary operator to manage a conditional that will allow you to display the default data, because none of the values can be initialized to null. 

Apply the corrections and send us the link again. 

https://github.com/cornensue/Conditional-Profile-Card/blob/45a1ba904e72170cfb7593a8b118e03d2e27f4c3/src/js/app.js#L36

**Comment by keikeka** [comment]
Cornelio, 
This issue you have not yet corrected. 
You are missing this to pass the exercise. Apply it and send us the repo again.

**Comment by cornensue** [comment]
Hello, 

Actually I wanted to tell you. I am not able to figure out how to apply the ternary operator. I've been trying...

**Comment by keikeka** [comment]
Hi Cornelio,
Don't worry. You will have time later to apply this operator. 
For now, keep busy with the development of the final project.
